// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"aigc/internal/api"
	"aigc/internal/conf"
	"aigc/internal/db"
	"aigc/internal/repo"
	"aigc/internal/router"
	"aigc/internal/service"
	"gitlab.hudonggz.cn/yangchunping/go-infra/httpsrv"
)

// Injectors from wire.go:

func InitApp() (*httpsrv.Server, error) {
	viper, err := conf.ProvideViper()
	if err != nil {
		return nil, err
	}
	config, err := conf.ProvideConfig(viper)
	if err != nil {
		return nil, err
	}
	sqlDB, err := db.ProvideSQLDB(config)
	if err != nil {
		return nil, err
	}
	logRepo := repo.NewSqliteLogRepo(sqlDB)
	logService := service.NewLogService(logRepo)
	logHandler := api.NewLogHandler(logService)
	server := ProvideHTTPServer(config, logHandler)
	return server, nil
}

// wire.go:

// ProvideHTTPServer 适配器：它不仅提取配置，还负责向 Wire 索要所有的 Handler，并完成路由组装
func ProvideHTTPServer(c *conf.Config, logHandler *api.LogHandler) *httpsrv.Server {

	srv := httpsrv.New(c.ServerAddr)
	router.RegisterRoutes(srv, logHandler)

	return srv
}
