// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"aigc/internal/api"
	"aigc/internal/conf"
	"aigc/internal/data"
	"aigc/internal/repo"
	"aigc/internal/router"
	"aigc/internal/service"
	"gitlab.hudonggz.cn/yangchunping/go-infra/httpsrv"
)

// Injectors from wire.go:

func InitApp() (*httpsrv.Server, error) {
	viper, err := conf.ProvideViper()
	if err != nil {
		return nil, err
	}
	config, err := conf.ProvideConfig(viper)
	if err != nil {
		return nil, err
	}
	db, err := data.NewDB(config)
	if err != nil {
		return nil, err
	}
	cache, err := data.ProvideRedisCache(config)
	if err != nil {
		return nil, err
	}
	dataData := &data.Data{
		DB:    db,
		Cache: cache,
	}
	logRepo := repo.NewSqliteLogRepo(dataData)
	logService := service.NewLogService(logRepo)
	logHandler := api.NewLogHandler(logService)
	handlers := &api.Handlers{
		LogHandler: logHandler,
	}
	server := ProvideHTTPServer(config, handlers)
	return server, nil
}

// wire.go:

// ProvideHTTPServer 适配器：它不仅提取配置，还负责向 Wire 索要所有的 Handler，并完成路由组装
func ProvideHTTPServer(c *conf.Config, handlers *api.Handlers) *httpsrv.Server {

	srv := httpsrv.New(c.Server.Addr)
	router.RegisterRoutes(srv, handlers)

	return srv
}
